---
title: Conclusions
author: 
date: 
output: 
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
---
```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

## Take home message

We have found three effects that we want to discuss for one last time.

<ul>
<li>There is a positive correlation between GPD and crimes, except for rape, with which the relationship seems either negative or very small depending on which analysis we are looking at (EDA or regressions). At a first glance we thought the positive relationship between GDP and most crimes wasn't a good instance because a wealthier state will have less criminality than a poorer state. However after thinking a little bit about the possible social reasons behind it we thought that this might be caused by the social distance between poor and rich people. In a wealthier state the distance between wealthier and poorer might be high. This might induce more people to commit violent crimes to gain money or reduce debt. This might also explain why there is a lower, if not negative, effect for rape. In fact, out of the four crimes that we considered this is the one that is least related to possible wealth change in the individual that commits the crime. Although, these are only supposition, therefore we looked up and research finding a vast literature on how higher GDP has on average a positive effect on criminality. It results that there could be some simultaneous causality considerations to do, since GDP, education, unemployment and poverty are strictly linkes factors. 
<br>Some references are [*Effect of GDP on Violent Crime, Northrup, Klaer*](https://smartech.gatech.edu/bitstream/handle/1853/51649/Klaer&NorthrupEconometricsReport.pdf), [*The Relationship between Crime and Economic Growth in Malaysia: Re-Examine Using Bound Test Approach, 2016, Mulok, Kogid, Lily, Asid *](https://www.researchgate.net/publication/309737921_The_Relationship_between_Crime_and_Economic_Growth_in_Malaysia_Re-Examine_Using_Bound_Test_Approach) </li>
<li>There is a negative correlation between education and criminality, this also can be reasonable since the education not only increases the hard skills, but also teaches people how to live in a civilized society, as well as it creates networks (easier to get help) and awareness on social problems. </li>
<li> We expected a negative correlation also between mental health spending and violent crimes, since taking care of possible dangerous people could reduce the impact on criminality, or at least reduce the relapse. Although our results are inconclusive and incoherent, some results indicates a positive correlation and others a negative relationship. One reason between inconsistency in regression results with the scatterplots could come from the fact that looking at the scatterplot alone we would consider a correlation which doesn't keep as constant all other variables which potentially could influenced both mental health expenditure and criminality. We think there may be a problem of endogeneity.</li>
<li> Indeed, another finding has been that mental health expenditure is higher in higher educated states, which in turns has a decreasing effect on criminality. This is only an example of how easy is to end up in some confounders. </li>
</ul>

## Limitations and Future work

We think out research idea on questions and criminality is interesting. Although it's also vague a big, with many potential drawbacks and, consequently, with many improvements that can inspire future work:

* We have included some control/independent variables in our regression model, although there could be still omitted variables which could create a bias. We used Fixed Effect method to eliminate bias coming from omitted variables which are time-invariant, such as characteristics specific to the State. But, FE doesn't consider omitted variables which are time-varying. Future work could consist in adding other variables, an example could be the number of police officers in a state, as well as the number of protest in a year in a certain state. Additionally, as we have seen GDP plays an important role, we may be interested in studying the effect of wealth disparity in a State on criminality.
* Always related to our analysis part, we are not proficient in machine learning, algorithm and modelling. By using other methods rather than econometric regressions, maybe our analysis could be improved
* A limitation is also in the sample. Our sample is made of 51 (52 cosnidering US as whole too) states over 10 years. The time-span isn't extremely big and in 10 years each state might not vary that much. Another limitation in the variation of variables comes from the fact that all states are part of the United States which shares the same politics at federal levels and similar cultures and backgrounds. The basic idea is that more variation in the regressors allows you to more confidently pin down the relationship between dependent variable and explanatory variables in a regression. To the contrary, the less variation of the regressor, the less precise the estimate. For this reason it could be interesting to increase the sample both in the time and unit dimension. Future work could involve a larger sample by searching for data on years prior to 2004 and/or for data in european, south-american and asian countries, etc... The only problem we encountered with this is that little collection of data on mental health expenditure is available, and even if there is, it's full of missing values, or with limited access. 
