---
title: Introduction
author: 
date: 
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
---

```{r, echo = FALSE, message = FALSE, warning=FALSE}
source(here::here("scripts/setup.R"))
```


## Overview and Motivation

When thinking at welfare and government expenditure in health, we often focus on physical health and not much in mental health. Starting this project our main idea was to study the relationship between Mental Health Services and Homicides. Later, we moved to a broader view to study which are the factor that mostly impact criminality in a developed country. 

After looking up for relevant data-sets on the internet, we decided to concentrate on United States of America, looking at data for each state.

The main motivation behind our project is our interest in social sciences and policies. Indeed, before starting, we decided for this topic because, possibly, our results could be interesting for a policy maker in taking decisions on education and mental health services expenditure and provision, as well as other factors.

## Related Work

### Project Objectives

The objective of this project is to understand whether the variables we have found have an impact on criminality and if they do, how they affect it (negatively or positively and significantly or not). 

We will focus on education, mental health expenditure by the governments, GDP and composition of the population.

Our aim is to identify potential policy targets in dealing with criminality and, consequently, quality of life in a Country/State. 

### Project's Outline
The project has been organized in different phases, all carried through the software R. 
In this section we will explain how we organized our work for you to have a clear idea of our project. 

We start by searching relevant data-sets on the internet and looking for variables of interest. Then, we proceed by cleaning and tidying each of them. This process is done by trying to have each data-set in the same form, to ease a later analysis of them. 
We create the whole final data-set with all the wanted information from the different sources. 

Then, we begin the Explanatory Data Analysis exploiting visualization tools and summarizing main characteristics of the data-set.

Finally, we analyze the results of panel data regressions and previous findings to answer our research questions and sum up the main take-home messages.

## Research questions

The research questions we will try answering throughout our project are:

<ul>
  <li>Is there any relationship between expenditure for mental health by the government and criminality?</li>
  <li>Is the level of education and wealth (through GDP) of a State relevant for its level of criminality?</li>
  <li>Is the composition of the population, in terms of both age and ethnicity, relevant for criminality in the area? </li>
  <li>Is mental health expenditure affected by how much the population is educated or by GDP of the country? </li>
</ul>
Given the questions posed above, the answers we will search for in our project could lead a reader to question himself on how to exploit these presences of correlation to reach a lower level of criminality. Though, the latter consideration makes sense only if we are able to find significant relationship between the different variables. 