---
draft: false
title: Limitations and Future work
weight: 35
---


We think our research questions on criminality is interesting. Although it's also vague, with many potential drawbacks and, consequently, with many improvements that can inspire future work:

* We have included some control/independent variables in our regression model, although there could be still omitted variables which could create a bias. We used Fixed Effect method to eliminate bias coming from omitted variables which are time-invariant, such as characteristics specific to the State. But FE doesn't consider omitted variables which are time-varying. Future work could consist in adding other variables. An example could be the number of police officers in a state, as well as the number of protests in a year in a certain state. Additionally, as we have seen GDP plays an important role, we may be interested in studying the effect of wealth disparity in a State on criminality.
* Always related to our analysis part, we are not proficient in machine learning, algorithm and modelling. By using other methods rather than econometric regressions, maybe our analysis could be improved.
* A limitation stands also in our sample. Our sample is made of 51 (52 cosnidering US as a whole too) states over 10 years. The time-span isn't extremely big and in 10 years each state might not vary that much. Another limitation in the variation of variables comes from the fact that all states are part of the United States which shares the same politics at federal level and similar culture and backgrounds. The basic idea is that more variation in the regressors allows you to more confidently pin down the relationship between dependent variable and explanatory variables in a regression. To the contrary, the less variation of the regressors, the less precise the estimates. For this reason it could be interesting to increase the sample both in the time and unit dimension. Future work could involve a larger sample by searching for data on years prior to 2004 and/or for data in european, south-american and asian countries, etc... The only problem we encountered with this is that little collection of data on mental health expenditure is available, and even if there is, it's full of missing values, or with limited access, for countries different from the US.
