---
draft: false
title: Take home message
weight: 30
---

Among our findings, we would like to discuss some effects for one last time.

<ul>
  <li>There is a positive correlation between GPD and crimes, except for rape, with which the relationship seems either negative or very small depending on which analysis we are looking at (EDA or regressions). At a first glance we thought the positive relationship between GDP and most crimes wasn't a good instance because we expected a wealthier state to have less criminality than a poorer state. However after thinking a little bit about the possible social reasons behind it we thought that this might be caused by the social distance between poor and rich people. In a wealthier state the distance between wealthier and poorer might be high. This might induce more people to commit violent crimes to gain money or reduce debt. This might also explain why there is a lower, if not negative, effect for rape. In fact, out of the four crimes that we considered, this is the one that is least related to possible wealth change in the individual that commits the crime. Although, these are only supposition, therefore we looked up and researched, finding a vast literature on how higher GDP has on average a positive effect on criminality. It results that there could be some simultaneous causality considerations to do, since GDP, education, unemployment and poverty are strictly linkes factors. 
<br>Some references are [*Effect of GDP on Violent Crime, Northrup, Klaer*](https://smartech.gatech.edu/bitstream/handle/1853/51649/Klaer&NorthrupEconometricsReport.pdf){target="_blank"}, [*The Relationship between Crime and Economic Growth in Malaysia: Re-Examine Using Bound Test Approach, 2016, Mulok, Kogid, Lily, Asid *](https://www.researchgate.net/publication/309737921_The_Relationship_between_Crime_and_Economic_Growth_in_Malaysia_Re-Examine_Using_Bound_Test_Approach){target="_blank"} </li>
<li>There is a negative correlation between education and criminality, this also can be reasonable since the education not only increases the hard skills, but also teaches people how to live in a civilized society, as well as it creates networks (easier to get help) and awareness on social problems. </li>
<li> We expected a negative correlation also between mental health spending and violent crimes, since taking care of possible dangerous people could reduce the impact on criminality, or at least reduce the relapse. Although, our results are inconclusive and incoherent, some results indicates a positive correlation and others a negative relationship. One reason behind inconsistency in regression results with the scatterplots could come from the fact that looking at the scatterplot alone we would consider a correlation which doesn't keep as constant all other variables which potentially could influence both mental health expenditure and criminality. We think there may be a problem of endogeneity.</li>
  <li> Indeed, another finding has been that mental health expenditure is higher in higher educated states, which in turns has a decreasing effect on criminality. This is only an example of how easy is to end up in some confounders while doing a regression. </li>
  </ul>